### ISSUE TITLE
Support for PHP 8.0

### ISSUE THREAD

**Issue by aftabnaveed** [andreas-glaser/php-helpers#2]
Hi, 

This package is currently restrained to use PHP ^7 can it be upgraded to PHp 8.0?

```json
"require": {
    "php": "^7",
    "ext-mbstring": "*",
    "ext-json": "*"
  },
```

**Comment by andreas-glaser** [comment]
Here you go:

https://github.com/andreas-glaser/php-helpers/releases/tag/1.2.0
